# copied largely from boost hana and pybind11 .travis config

language: c++
sudo: false


default_sources: &sources
  - ubuntu-toolchain-r-test
  - kubuntu-backports
  - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
  - deadsnakes

cache:
  apt: true # this currently does nothing?
  directories:
    - $HOME/.ccache
    - $HOME/.cache/pip
    - $HOME/Library/Caches/pip
    - ${TRAVIS_BUILD_DIR}/deps/llvm-3.6.2
    - ${TRAVIS_BUILD_DIR}/deps/llvm-3.7.1
    - ${TRAVIS_BUILD_DIR}/deps/llvm-3.8.0
    - ${TRAVIS_BUILD_DIR}/deps/llvm-3.9.0
    - ${TRAVIS_BUILD_DIR}/deps/boost-1.59.0
    - ${TRAVIS_BUILD_DIR}/deps/boost-1.60.0
    - ${TRAVIS_BUILD_DIR}/deps/boost-1.61.0
    - ${TRAVIS_BUILD_DIR}/deps/boost-1.62.0
    - ${TRAVIS_BUILD_DIR}/deps/boost-1.63.0

matrix:
  include:

    - os: linux
      dist: trusty
      env: OS=LU14 UNIT=T GCC=5
      language: c++
      addons:
        apt:
          sources: *sources
          packages: [g++-5, libboost-iostreams-dev, libboost-system-dev]

    - os: linux
      dist: trusty
      env: OS=LU14 UNIT=T GCC=6
      language: c++
      addons:
        apt:
          sources: *sources
          packages: [g++-6, libboost-iostreams-dev, libboost-system-dev]

    - os: linux
      dist: trusty
      env: OS=LU14 UNIT=T GCC=6 PY=3
      language: c++
      addons:
        apt:
          sources: *sources
          packages: [g++-6, libboost-iostreams-dev, libboost-system-dev, python3]

    - os: linux
      dist: trusty
      env: OS=LU14 UNIT=T BOOST_VERSION=default
      language: c++
      addons:
        apt:
          sources: *sources
          packages: [clang++-3.5]

    - os: osx
      env: OS=OSX6 UNIT=T BOOST_VERSION=default
      language: c++
      osx_image: xcode6

    - os: osx
      env: OS=OSX8 UNIT=T BOOST_VERSION=default PY=3
      language: c++
      osx_image: xcode8

    - os: linux
      env: OS=LU12 UNIT=T LLVM_VERSION=default BOOST_VERSION=1.59.0
      language: c++

    - os: linux
      env: OS=LU12 UNIT=T GCC=6 BOOST_VERSION=default
      language: c++
      addons:
        apt:
          sources: *sources
          packages: [g++-6]

before_install:
  - CC=gcc-$GCC; CXX=g++-$GCC
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - source tools/build_utils.sh
  - if [[ "${LLVM_VERSION}" == "default" ]]; then LLVM_VERSION=3.9.0; fi
  - if [[ "${BOOST_VERSION}" == "default" ]]; then BOOST_VERSION=1.63.0; fi
  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi
  - if [[ ! "$PY" ]]; then PY=2; fi
  - export PATH=/usr/lib/ccache:$PATH
  - export CCACHE_DISABLE=false
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then CC=clang; CXX=clang++; fi
  - (echo FINDING_CCACHE in $HOME && find $HOME -name .ccache)
install:
  - travis_get_cmake
  - if [[ "$LLVM_VERSION" ]]; then get_clang $DEPS_DIR $LLVM_VERSION; fi
  - if [[ "$BOOST_VERSION" ]]; then get_boost $DEPS_DIR $BOOST_VERSION; fi
  - if [ ! -z ${DOCS+x} ]; then get_doxygen; fi
  - |
    if [[ $PY == "3" ]]; then
      if [[ $TRAVIS_OS_NAME == "osx" ]]; then brew install python3; fi
      python3 -m ensurepip
      export PIP=pip3
    else
      export PIP=pip
    fi
  - which pip$PY
  - $PIP install -rrequirements.txt codecov
  # - pip install --verbose jinja2
  # - pip$PY install --verbose jinja2

before_script:
  - cd ${TRAVIS_BUILD_DIR}

script:
  - |
    if [[ $UNIT == T ]]; then
      (python$PY tools/cmake_build_and_run_pytest.py && codecov)
      echo REMOVE THIS IF CMAKE CALLS IT !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
      ccache -s
    elif [[ $DOSC == T ]]; then
      (cd docs && make html)
    else
      echo "unknown config, nothing done"
    fi

after_script:
  - (echo FINDING_CCACHE in $HOME && find $HOME -name .ccache)
