# copied largely from boost hana and pybind11 .travis config

language: c++
sudo: false

env:
  matrix:
    - TRAVIS_EMPTY_JOB_WORKAROUND=true

addons:
  apt:
    packages:
      - g++-5
      - g++-6
      - cmake
      - cmake-data
      - python-pip
      - python-numpy
      - python-pandas
      - libz-dev
      - libbz2-dev
      - libboost-iostreams-dev
      - libboost-system-dev
    sources: &sources
      - ubuntu-toolchain-r-test
      - kubuntu-backports
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
      - deadsnakes

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps/llvm-3.6.2
    - ${TRAVIS_BUILD_DIR}/deps/llvm-3.7.1
    - ${TRAVIS_BUILD_DIR}/deps/llvm-3.8.0
    - ${TRAVIS_BUILD_DIR}/deps/llvm-3.9.0
    - ${TRAVIS_BUILD_DIR}/deps/boost-1.59.0
    - ${TRAVIS_BUILD_DIR}/deps/boost-1.60.0
    - ${TRAVIS_BUILD_DIR}/deps/boost-1.61.0
    - ${TRAVIS_BUILD_DIR}/deps/boost-1.62.0
    - ${TRAVIS_BUILD_DIR}/deps/boost-1.63.0
    - ${TRAVIS_BUILD_DIR}/build_setup_py_Release

matrix:
  exclude:
    - env: TRAVIS_EMPTY_JOB_WORKAROUND=true

  include:
    - os: linux
      dist: trusty
      env: UNIT_TESTS=true GCC=5
      compiler: gcc
    - os: linux
      dist: trusty
      env: UNIT_TESTS=true GCC=6
      compiler: gcc
    - os: linux
      env: UNIT_TESTS=true GCC=5
      compiler: gcc
    - os: linux
      env: UNIT_TESTS=true GCC=6
      compiler: gcc
    - os: linux
      env: UNIT_TESTS=true LLVM_VERSION=3.6.2 BOOST_VERSION=default
      compiler: clang
    - os: osx
      env: UNIT_TESTS=true BOOST_VERSION=default
      osx_image: xcode6
    - os: osx
      env: UNIT_TESTS=true BOOST_VERSION=default
      osx_image: xcode7
    - os: osx
      env: UNIT_TESTS=true BOOST_VERSION=default
      osx_image: xcode8
    - os: linux
      env: UNIT_TESTS=true LLVM_VERSION=default BOOST_VERSION=1.59.0
      compiler: clang

before_install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - source tools/build_utils.sh
  - if [[ "${LLVM_VERSION}" == "default" ]]; then LLVM_VERSION=3.9.0; fi
  - if [[ "${BOOST_VERSION}" == "default" ]]; then BOOST_VERSION=1.63.0; fi
  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi
install:
  - CC=gcc-$GCC; CXX=g++-$GCC
  - if [[ $TRAVIS_OS_NAME == "osx" ]]; then CC=clang; CXX=clang++; fi
  - travis_get_cmake
  - if [[ "$LLVM_VERSION" ]]; then get_clang $DEPS_DIR $LLVM_VERSION; fi
  - if [[ "$BOOST_VERSION" ]]; then get_boost $DEPS_DIR $BOOST_VERSION; fi
  - if [[ "${DOCUMENTATION}" == "true" ]]; then get_doxygen; fi
  - pip install --user sphinx numpy pandas future jinja2 pytest pytest-cov pytest-sugar pytest-xdist hypothesis enum34 codecov
  - (cd external/hacked_packages/pytest-cpp-0.4 && pip install --user .)

before_script:
  - cd ${TRAVIS_BUILD_DIR}

script:
  - |
    if [[ "${UNIT_TESTS}" == "true" ]]; then
      (python tools/cmake_build_and_run_pytest.py && codecov)
    elif [[ "${DOCUMENTATION}" == "true" ]]; then
      (cd docs && make html)
    fi


