name: rif
dependencies:
 - python=3
 - numpy=1.13
 - PyYAML
 - colorama
 - future
 - jinja2
 - pandas
 - xarray
 - pytest
 - pytest-cov
 - sphinx_rtd_theme
 - mock
 - pip
 - pip:
   - external/hacked_packages/pytest-cpp-0.4
   - breathe
   - hypothesis
   - pytest-sugar
   - pytest-xdist
