name: rif
dependencies:
 - python>=3.5
 - numpy=1.13.3
 - PyYAML
 - colorama
 - future
 - jinja2
 - pandas
 - xarray
 - pytest
 - pytest-cov
 - sphinx_rtd_theme
 - mock
 - seaborn
 - dask
 - pip:
   - external/hacked_packages/pytest-cpp-0.4
   - breathe
   - hypothesis
   - pytest-sugar
   - pytest-xdist
   - parsimonious
   - tqdm
   - homog
